export type ScenarioStory = {
  id: string;
  title: string;
  severity: 'medium' | 'high' | 'critical';
  time: string;
  category: string;
  executiveAngle: string;
  situation: string;
  systemImpact: string;
  mcpEvidence: string;
  humanDecision: string;
  injector: string;
  agentRun: string;
  outcome: string;
  metrics: Array<{ label: string; value: string; tone: 'neutral' | 'good' | 'warn' | 'bad' }>;
};

export const scenarioStories: ScenarioStory[] = [
  {
    id: 'morning_triage',
    title: 'Morning Triage: Pre-Market Health Sweep',
    severity: 'critical',
    time: '06:15 ET',
    category: 'Session, Orders, Reference Data',
    executiveAngle: 'Show how MCP turns scattered pre-market checks into one controlled incident workflow.',
    situation: 'ARCA is down after maintenance, ACME has a corporate-action symbol change, and ZEPH is missing from reference data.',
    systemImpact: 'Institutional orders are stuck before the open while symbol issues can create avoidable rejects.',
    mcpEvidence: 'The agent checks sessions, queries affected orders, validates symbols, and records every tool call in trace.',
    humanDecision: 'The operator approves session recovery and symbol remediation before any order release.',
    injector: 'Inject a reject spike after the baseline triage to prove the agent separates new pressure from root cause.',
    agentRun: 'Agent Run can execute the approved workbook while the human watches trace evidence update.',
    outcome: 'The desk sees blocked flow, verified fixes, and remaining risk in one executive-readable chain.',
    metrics: [
      { label: 'Open Orders', value: '44', tone: 'bad' },
      { label: 'Primary Venue', value: 'ARCA down', tone: 'bad' },
      { label: 'Mode', value: 'Approve workbook', tone: 'good' },
    ],
  },
  {
    id: 'bats_startup_0200',
    title: 'BATS Extended-Hours Startup',
    severity: 'medium',
    time: '02:05 ET',
    category: 'Session, Orders, Reference Data',
    executiveAngle: 'Show an overnight desk issue where the right sequence decision matters more than speed.',
    situation: 'BATS rejects Logon after an invalid SequenceReset while IEX is healthy and other venues are unavailable.',
    systemImpact: 'Eight GTC orders are blocked and two ETF symbols are not loaded for extended hours.',
    mcpEvidence: 'MCP checks FIX sessions, exposes the sequence mismatch, loads missing symbols, and validates order release.',
    humanDecision: 'The operator confirms sequence recovery before approving the workbook.',
    injector: 'Inject a sequence gap or reject spike to show re-triage before continuing the plan.',
    agentRun: 'Agent Run works only after approval and reports evidence after each simulated step.',
    outcome: 'The demo proves human approval plus MCP tooling can recover a live-desk style session issue.',
    metrics: [
      { label: 'Blocked Orders', value: '14', tone: 'warn' },
      { label: 'BATS', value: 'down', tone: 'bad' },
      { label: 'Fallback', value: 'IEX healthy', tone: 'good' },
    ],
  },
  {
    id: 'venue_degradation_1030',
    title: 'Venue Degradation: NYSE Latency Crisis',
    severity: 'critical',
    time: '10:32 ET',
    category: 'Session, Orders',
    executiveAngle: 'Show a market-hours incident where venue health directly threatens client execution quality.',
    situation: 'NYSE latency degrades while institutional orders continue to queue.',
    systemImpact: 'Twenty open orders are exposed to slow acknowledgements and potential SLA pressure.',
    mcpEvidence: 'MCP correlates latency, session state, and affected orders instead of treating the alert in isolation.',
    humanDecision: 'The operator decides whether to pause, reroute, or continue after seeing quantified blast radius.',
    injector: 'Inject a venue outage to show how the workbook changes when degraded becomes down.',
    agentRun: 'Agent Run follows the approved recovery path and leaves a trace of each session and order check.',
    outcome: 'Executives see how the desk avoids blind rerouting and keeps evidence tied to decisions.',
    metrics: [
      { label: 'Open Orders', value: '20', tone: 'bad' },
      { label: 'Venue', value: 'NYSE degraded', tone: 'bad' },
      { label: 'Evidence', value: 'Trace + FIX wire', tone: 'good' },
    ],
  },
  {
    id: 'midday_chaos_1205',
    title: 'Midday Chaos: TWAP Stale Data + ACK Backlog',
    severity: 'critical',
    time: '12:05 ET',
    category: 'Algo, Market Data, Orders',
    executiveAngle: 'Show compound-incident handling without letting the agent continue an obsolete plan.',
    situation: 'TWAP execution is drifting while market-data freshness and acknowledgement backlog must be separated.',
    systemImpact: 'The desk risks poor execution quality if the agent optimizes the wrong failure mode.',
    mcpEvidence: 'MCP inspects algo state, session status, orders, and trace before recommending next action.',
    humanDecision: 'The operator approves only the bounded workbook that matches the verified cause.',
    injector: 'Inject SLA breach or venue pressure mid-run to force plan reassessment.',
    agentRun: 'Agent Run must pause and re-triage when injected pressure changes the scope.',
    outcome: 'The visible value is disciplined triage, not autonomous activity for its own sake.',
    metrics: [
      { label: 'Open Orders', value: '2', tone: 'warn' },
      { label: 'Scenario', value: 'compound', tone: 'bad' },
      { label: 'Guardrail', value: 'human approval', tone: 'good' },
    ],
  },
  {
    id: 'eod_moc_1530',
    title: 'EOD MOC Crunch',
    severity: 'high',
    time: '15:31 ET',
    category: 'Orders, Regulatory, Reference Data',
    executiveAngle: 'Show time-boxed close pressure where approval discipline matters.',
    situation: 'Market-on-close pressure builds while validation and regulatory constraints must be checked quickly.',
    systemImpact: 'Twenty-five open orders need a safe decision before the closing window tightens.',
    mcpEvidence: 'MCP validates orders and maps the workbook to manual commands an operator can audit.',
    humanDecision: 'The operator approves the full workbook only after validation clears the release path.',
    injector: 'Inject SLA breach to show escalation without skipping controls.',
    agentRun: 'Agent Run can execute approved checks while surfacing exceptions immediately.',
    outcome: 'The demo shows acceleration with governance, not shortcutting.',
    metrics: [
      { label: 'Open Orders', value: '25', tone: 'bad' },
      { label: 'Window', value: 'close', tone: 'warn' },
      { label: 'Control', value: 'validation first', tone: 'good' },
    ],
  },
  {
    id: 'open_volatility_0930',
    title: 'Opening Volatility: LULD Circuit Breaker',
    severity: 'high',
    time: '09:35 ET',
    category: 'Orders, Regulatory, Session',
    executiveAngle: 'Show that market structure events should not be mistaken for infrastructure failures.',
    situation: 'Opening volatility and LULD pressure change what the desk is allowed to do.',
    systemImpact: 'Orders may be blocked for regulatory reasons even when technology is functioning.',
    mcpEvidence: 'MCP checks venue state, order flags, and regulatory context before proposing action.',
    humanDecision: 'The operator confirms halt context before releasing or rerouting anything.',
    injector: 'Inject LULD halt on an active symbol to show the distinction clearly.',
    agentRun: 'Agent Run updates the workbook only after the market-event state is verified.',
    outcome: 'The value is fewer false infrastructure escalations and cleaner regulatory evidence.',
    metrics: [
      { label: 'Open Orders', value: '11', tone: 'warn' },
      { label: 'Event', value: 'LULD', tone: 'bad' },
      { label: 'Decision', value: 'verify halt', tone: 'good' },
    ],
  },
  {
    id: 'afterhours_dark_1630',
    title: 'After-Hours Dark Pool Crisis',
    severity: 'medium',
    time: '16:32 ET',
    category: 'Session, Orders',
    executiveAngle: 'Show post-close routing decisions when only specific venues are valid.',
    situation: 'Dark pool access is impaired after-hours while lit venues have different availability.',
    systemImpact: 'Large block flow can stall if the desk treats every venue the same.',
    mcpEvidence: 'MCP separates market-hours availability from actual dark-pool failure.',
    humanDecision: 'The operator approves the route only after venue eligibility is confirmed.',
    injector: 'Inject venue outage to show what happens when the fallback also becomes unavailable.',
    agentRun: 'Agent Run executes only the approved simulated routing checks.',
    outcome: 'Executives see venue eligibility, not just alert noise.',
    metrics: [
      { label: 'Open Orders', value: '14', tone: 'warn' },
      { label: 'Session Mix', value: 'after-hours', tone: 'warn' },
      { label: 'Proof', value: 'FIX + trace', tone: 'good' },
    ],
  },
  {
    id: 'iex_recovery_1400',
    title: 'IEX Session Recovery',
    severity: 'medium',
    time: '14:03 ET',
    category: 'Session, Orders',
    executiveAngle: 'Show standard session recovery with evidence and approval.',
    situation: 'IEX requires recovery while active orders need status confirmation.',
    systemImpact: 'Eighteen open orders need session confidence before release.',
    mcpEvidence: 'MCP checks session state, validates affected orders, and records the recovery trail.',
    humanDecision: 'The operator decides whether to reconnect, reset, or hold flow.',
    injector: 'Inject seq_gap to demonstrate recovery path selection.',
    agentRun: 'Agent Run can proceed once the operator approves the exact recovery action.',
    outcome: 'The scenario demonstrates repeatable desk hygiene.',
    metrics: [
      { label: 'Open Orders', value: '18', tone: 'warn' },
      { label: 'Venue', value: 'IEX', tone: 'neutral' },
      { label: 'Action', value: 'recover session', tone: 'good' },
    ],
  },
  {
    id: 'predawn_adrs_0430',
    title: 'Predawn ADR Pricing Crisis',
    severity: 'medium',
    time: '04:35 ET',
    category: 'Session, Orders, Reference Data',
    executiveAngle: 'Show early-morning reference data risk before the US open.',
    situation: 'ADR pricing and venue state need reconciliation before orders are released.',
    systemImpact: 'Fourteen orders can be mispriced or rejected if data is stale.',
    mcpEvidence: 'MCP checks reference data, sessions, and affected order set together.',
    humanDecision: 'The operator approves data correction before flow resumes.',
    injector: 'Inject client message or reject spike to test communication pressure.',
    agentRun: 'Agent Run follows the approved evidence path and reports residual risk.',
    outcome: 'The desk sees why documentation plus MCP tools reduce morning surprises.',
    metrics: [
      { label: 'Open Orders', value: '14', tone: 'warn' },
      { label: 'Risk', value: 'ADR pricing', tone: 'bad' },
      { label: 'Fix', value: 'reference data', tone: 'good' },
    ],
  },
  {
    id: 'preopen_auction_0900',
    title: 'Pre-Open Auction: Imbalance Crisis',
    severity: 'high',
    time: '09:02 ET',
    category: 'Orders, Market Data, Regulatory',
    executiveAngle: 'Show how MCP supports high-pressure auction decisions.',
    situation: 'Auction imbalance and market data require quick validation before the open.',
    systemImpact: 'Seventeen orders may be exposed to auction and compliance constraints.',
    mcpEvidence: 'MCP gathers order, market data, and regulatory context into one workbook.',
    humanDecision: 'The operator chooses hold, release, or adjust after seeing evidence.',
    injector: 'Inject SLA breach to show deadline pressure without losing control.',
    agentRun: 'Agent Run continues only inside the approved workbook.',
    outcome: 'The user can see pressure, controls, and evidence in the same story.',
    metrics: [
      { label: 'Open Orders', value: '17', tone: 'bad' },
      { label: 'Window', value: 'pre-open', tone: 'warn' },
      { label: 'Control', value: 'approval gate', tone: 'good' },
    ],
  },
  {
    id: 'ssr_and_split_1130',
    title: 'SSR + Stock Split Crisis',
    severity: 'critical',
    time: '11:34 ET',
    category: 'Orders, Regulatory, Reference Data',
    executiveAngle: 'Show compound regulatory and reference-data risk.',
    situation: 'Short-sale restriction and split data interact with active order handling.',
    systemImpact: 'Fourteen open orders can fail compliance or pricing checks if handled incorrectly.',
    mcpEvidence: 'MCP validates symbols, restrictions, and orders before recommending action.',
    humanDecision: 'The operator approves only compliant remediation.',
    injector: 'Inject reject spike to prove the agent rechecks scope under pressure.',
    agentRun: 'Agent Run executes approved validation and remediation steps with trace evidence.',
    outcome: 'Executives see the difference between speed and controlled speed.',
    metrics: [
      { label: 'Open Orders', value: '14', tone: 'bad' },
      { label: 'Risk', value: 'SSR + split', tone: 'bad' },
      { label: 'Gate', value: 'compliance', tone: 'good' },
    ],
  },
  {
    id: 'twap_slippage_1000',
    title: 'TWAP Slippage Alert',
    severity: 'high',
    time: '10:05 ET',
    category: 'Algo, Session, Orders',
    executiveAngle: 'Show AI-assisted algo monitoring without pretending the model owns execution.',
    situation: 'A TWAP order is slipping while BATS session quality must be verified.',
    systemImpact: 'Execution quality and client confidence are at risk.',
    mcpEvidence: 'MCP inspects algo progress, schedule deviation, session state, and affected orders.',
    humanDecision: 'The operator approves whether to pause, adjust, or reroute.',
    injector: 'Inject venue pressure to show how algo recommendations change.',
    agentRun: 'Agent Run performs approved checks and stops at decision points.',
    outcome: 'The demo shows agent support for execution oversight with human control.',
    metrics: [
      { label: 'Open Orders', value: '5', tone: 'warn' },
      { label: 'Algo', value: 'TWAP', tone: 'warn' },
      { label: 'Human', value: 'owns action', tone: 'good' },
    ],
  },
  {
    id: 'vwap_vol_spike_1130',
    title: 'VWAP Over-Participation Crisis',
    severity: 'critical',
    time: '11:35 ET',
    category: 'Algo, Orders, Regulatory',
    executiveAngle: 'Show risk management for agent-assisted algo decisions.',
    situation: 'VWAP participation is too aggressive during a volatility spike.',
    systemImpact: 'The desk risks market impact or regulatory concern if action is automated blindly.',
    mcpEvidence: 'MCP compares participation, order state, and venue health before recommendation.',
    humanDecision: 'The operator approves a bounded adjustment or pause.',
    injector: 'Inject LULD or reject spike to test plan resilience.',
    agentRun: 'Agent Run can monitor and execute approved checks but cannot make unapproved trading decisions.',
    outcome: 'The executive takeaway is governed AI in execution workflows.',
    metrics: [
      { label: 'Open Orders', value: '5', tone: 'warn' },
      { label: 'Algo', value: 'VWAP', tone: 'bad' },
      { label: 'Control', value: 'bounded', tone: 'good' },
    ],
  },
  {
    id: 'is_dark_failure_1415',
    title: 'Dark Pool Failure + IS Shortfall',
    severity: 'high',
    time: '14:15 ET',
    category: 'Algo, Session, Orders',
    executiveAngle: 'Show hidden-liquidity failure with measurable execution impact.',
    situation: 'Dark pool connectivity and implementation shortfall must be diagnosed together.',
    systemImpact: 'The desk may miss liquidity or worsen execution if fallback is chosen blindly.',
    mcpEvidence: 'MCP ties session state, algo performance, and order eligibility together.',
    humanDecision: 'The operator approves fallback route or pause after seeing evidence.',
    injector: 'Inject venue outage to test fallback durability.',
    agentRun: 'Agent Run executes the approved proof path and reports what changed.',
    outcome: 'The scenario makes invisible market-structure risk visible.',
    metrics: [
      { label: 'Open Orders', value: '3', tone: 'warn' },
      { label: 'Venue', value: 'IEX degraded', tone: 'bad' },
      { label: 'Proof', value: 'algo + session', tone: 'good' },
    ],
  },
];

export const defaultStory = scenarioStories.find((story) => story.id === 'morning_triage') || scenarioStories[0];
